# Generated by Django 4.2.5 on 2023-10-06 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
