# Generated by Django 4.2.5 on 2023-10-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0002_alter_bug_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
