# Generated by Django 4.2.5 on 2023-10-17 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0003_alter_bug_bug_type_alter_bug_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(25), django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
