# Generated by Django 4.2.6 on 2023-10-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0005_auto_20231029_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_type',
            field=models.CharField(choices=[('FEAT', 'New Feature'), ('ERR', 'Error'), ('FUNC', 'Functional'), ('LOGIC', 'Logical'), ('FLOW', 'Workflow'), ('UIUX', 'Usability'), ('SEC', 'Security'), ('PERF', 'Performance'), ('COMP', 'Compatibility'), ('UNIT', 'Unit Level'), ('SYS', 'System Level'), ('OUT', 'Out of Bound')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('TODO', 'To-Do'), ('PLAN', 'Planning'), ('DESIGN', 'Designing'), ('PROTO', 'Prototyping'), ('WIP', 'Work in Progress'), ('TEST', 'Testing'), ('RNA', 'Review & Approval'), ('STAGE', 'Staging'), ('DEPLOY', 'Deployment'), ('DONE', 'Done')], max_length=6),
        ),
    ]
